name = "econolearn-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "ns-zgaesRm8Wu4B"
preview_id = "ns-zgaesRm8Wu4B"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "econolearn-jwt-secret-key-2024-development-secure"

[build]
command = "npm run build"
